# version: '3.8'

services:

  user-service:
    build:
      context: ./microservices/user-service
      dockerfile: Dockerfile.dev
    ports:
      - "4001:3001"
    volumes:
      - ./microservices/user-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/userDB
      - PORT=3001
      - JWT_SECRET=8f7d2b1e-4c3a-4e2b-8e7a-9c6d5b4a3f2e!@#RandomExtraStuff
      - CORS_ORIGIN=http://localhost:5173
    command: npm run dev

  student-service:
    build:
      context: ./microservices/student-service
      dockerfile: Dockerfile.dev
    ports:
      - "4002:3002"
    volumes:
      - ./microservices/student-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/studentDB
      - PORT=3002
      - JWT_SECRET=8f7d2b1e-4c3a-4e2b-8e7a-9c6d5b4a3f2e!@#RandomExtraStuff
      - USER_SERVICE_URL=http://user-service:3001
      - CORS_ORIGIN=http://localhost:5173
    command: npm run dev

  form-service:
    build:
      context: ./microservices/form-service
      dockerfile: Dockerfile.dev
    ports:
      - "4003:3003"
    volumes:
      - ./microservices/form-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/formDB
      - PORT=3003
      - JWT_SECRET=8f7d2b1e-4c3a-4e2b-8e7a-9c6d5b4a3f2e!@#RandomExtraStuff
      - USER_SERVICE_URL=http://user-service:3001
      - STUDENT_SERVICE_URL=http://student-service:3002
      - CORS_ORIGIN=http://localhost:5173
    command: npm run dev

  analytics-service:
    build:
      context: ./microservices/analytics-service
      dockerfile: Dockerfile.dev
    ports:
      - "4004:3004"
    volumes:
      - ./microservices/analytics-service:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/analyticsDB
      - PORT=3004
      - JWT_SECRET=8f7d2b1e-4c3a-4e2b-8e7a-9c6d5b4a3f2e!@#RandomExtraStuff
      - CORS_ORIGIN=http://localhost:5173
    command: npm run dev

  
  mongo:
    image: mongo:8.0
    ports:
      - "27018:27017"
    volumes:
      - mongo-dev-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\").ok' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s


  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    environment:
      # - VITE_API_URL=http://localhost:4001 # match dev ports
      - VITE_USER_SERVICE_URL=http://localhost:4001
      - VITE_STUDENT_SERVICE_URL=http://localhost:4002
      - VITE_FORM_SERVICE_URL=http://localhost:4003
      - VITE_ANALYTICS_SERVICE_URL=http://localhost:4004
    command: npm run dev

volumes:
  mongo-dev-data:
